name: DEPLOY

on:
  push:
    paths:
      - 'imagine-web/**'
      - 'datasets/allergen30.yaml'
      - '.github/workflows/deploy.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  deploy-web:
    name: Deploy Imagine-Web
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Install
      working-directory: imagine-web
      run: npm install
    
    - name: Build
      working-directory: imagine-web
      run: npm run build
        
    - name: NoJekyll
      run: touch imagine-web/build/.nojekyll
    
    - name: Setup Pages
      uses: actions/configure-pages@v5
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: imagine-web/build

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
